import type { ConnectorDefinition } from "./types";

const read = (id: string, label: string) => ({ id, label, direction: "read" as const, approvalRequired: false });
const write = (id: string, label: string, approvalRequired = true) => ({ id, label, direction: "write" as const, approvalRequired });

export const connectorCatalog: ConnectorDefinition[] = [
  {
    id: "github",
    provider: "GitHub",
    category: "signal",
    auth: "corsair_managed",
    packageName: "@corsair-dev/github",
    availability: "implemented",
    configKeys: ["GITHUB_TOKEN"],
    signalTypes: ["github_commit", "github_pull_request", "github_release"],
    capabilities: [read("repository.read", "Read repositories"), read("repository.read_pull_requests", "Read pull requests"), write("repository.create_pull_request", "Create pull request")],
    description: "One optional signal and execution source for technical product changes.",
  },
  {
    id: "slack",
    provider: "Slack",
    category: "signal",
    auth: "corsair_managed",
    packageName: "@corsair-dev/slack",
    availability: "documented",
    signalTypes: ["slack_message", "slack_mention"],
    capabilities: [read("messages.read", "Read messages"), write("messages.send", "Send message")],
    description: "Internal conversations, founder commands, alerts, and approval notifications.",
  },
  {
    id: "notion",
    provider: "Notion",
    category: "signal",
    auth: "corsair_managed",
    packageName: "@corsair-dev/notion",
    availability: "documented",
    signalTypes: ["notion_change"],
    capabilities: [read("pages.read", "Read pages"), write("pages.create", "Create page")],
    description: "Product, strategy, and documentation context.",
  },
  {
    id: "x",
    provider: "X",
    category: "execution",
    auth: "corsair_managed",
    availability: "documented",
    capabilities: [read("timeline.read", "Read timeline"), write("posts.create", "Create post")],
    description: "Social research and founder-approved draft execution where available.",
  },
  {
    id: "linkedin",
    provider: "LinkedIn",
    category: "execution",
    auth: "corsair_managed",
    availability: "documented",
    capabilities: [read("profile.read", "Read profile"), write("posts.create", "Create post")],
    description: "Founder-approved professional distribution.",
  },
  {
    id: "reddit",
    provider: "Reddit",
    category: "signal",
    auth: "corsair_managed",
    availability: "documented",
    signalTypes: ["reddit_discussion"],
    capabilities: [read("search.read", "Search discussions"), write("reply.draft", "Stage reply draft")],
    description: "Community discovery and human-posted response staging. Autonomous posting is disabled.",
  },
  {
    id: "hacker_news",
    provider: "Hacker News",
    category: "signal",
    auth: "none",
    availability: "documented",
    signalTypes: ["hacker_news_discussion"],
    capabilities: [read("search.read", "Read discussions"), write("reply.draft", "Stage reply draft")],
    description: "Public discussion discovery and human-posted response staging.",
  },
  {
    id: "google",
    provider: "Google",
    category: "signal",
    auth: "corsair_managed",
    availability: "documented",
    signalTypes: ["search_opportunity", "search_console_change"],
    capabilities: [read("search.read", "Read search opportunities"), read("analytics.read", "Read analytics")],
    description: "Search and product discovery signals.",
  },
  {
    id: "discord",
    provider: "Discord",
    category: "signal",
    auth: "corsair_managed",
    availability: "documented",
    signalTypes: ["discord_message"],
    capabilities: [read("messages.read", "Read messages"), write("messages.send", "Send message")],
    description: "Community signal source and approved notifications.",
  },
  {
    id: "product_hunt",
    provider: "Product Hunt",
    category: "execution",
    auth: "oauth",
    availability: "deferred",
    capabilities: [read("launch.read", "Read launch context"), write("launch.prepare", "Prepare launch assets")],
    description: "Campaign preparation capability; no unverified official publishing connector is assumed.",
  },
  {
    id: "tavily",
    provider: "Tavily",
    category: "research",
    auth: "api_key",
    availability: "implemented",
    configKeys: ["TAVILY_API_KEY"],
    capabilities: [read("search", "Search web")],
    description: "Discovery, market research, SERP, Reddit, and Hacker News search.",
  },
  {
    id: "firecrawl",
    provider: "Firecrawl",
    category: "research",
    auth: "api_key",
    availability: "implemented",
    configKeys: ["FIRECRAWL_API_KEY"],
    capabilities: [read("scrape", "Extract page"), read("crawl", "Crawl site")],
    description: "Deep page and documentation extraction.",
  },
  {
    id: "tinyfish",
    provider: "TinyFish",
    category: "research",
    auth: "api_key",
    availability: "implemented",
    configKeys: ["TINYFISH_API_URL"],
    capabilities: [read("browse", "Browse dynamic site"), read("interact", "Interact with site")],
    description: "Dynamic browser research fallback.",
  },
  {
    id: "groq",
    provider: "Groq",
    category: "llm",
    auth: "api_key",
    availability: "implemented",
    configKeys: ["GROQ_API_KEY"],
    capabilities: [read("complete", "Generate completion")],
    description: "Required MVP LLM provider for fast classification, extraction, and research.",
  },
  {
    id: "orcarouter",
    provider: "OrcaRouter",
    category: "llm",
    auth: "api_key",
    availability: "implemented",
    configKeys: ["ORCAROUTER_API_KEY"],
    capabilities: [read("complete", "Generate completion")],
    description: "Optional configurable LLM router for reasoning and writing.",
  },
];
